module.exports = {
  collectCoverageFrom: [
    "**/*.js",
    "!**/*.clio.js",
    "!coverage/**/*.js",
    "!jest.config.js",
    "!index.js",
    "!browser.js",
    "!common.js",
    "!gulpfile.js",
    "!highlight.js",
    "!jest-puppeteer.config.js",
    "!host/**/*",
    "!tests/**/*",
    "!docs/**/*",
  ],
  testPathIgnorePatterns: [
    "<rootDir>/jest.config.js",
    "<rootDir>/packages/rpc/test",
  ],
  coveragePathIgnorePatterns: [
    "<rootDir>/jest.config.js",
    "<rootDir>/packages/rpc",
    "<rootDir>/packages/cli",
    "<rootDir>/packages/run",
    "<rootDir>/packages/website",
    "<rootDir>/packages/playground",
    "<rootDir>/packages/highlight",
    "<rootDir>/packages/language-server",
  ],
  moduleFileExtensions: ["js", "json", "jsx", "ts", "tsx", "node", "toml"],
  testEnvironment: "node",
  testTimeout: 60000,
};
